### ISSUE TITLE
How to train VADNoiseModelEnhancer Model

### ISSUE THREAD

**Issue by zuowanbushiwo** [Speech-Interaction-Technology-Aalto-U/itsp#14]
Dear Sir
I like your project very much. I don't see any training script in your project. How should I train a model?
Thanks!

**Comment by tombackstrom** [comment]
The model is based on the paper "Jean-Marc Valin. A hybrid DSP/deep learning approach to real-time full-band speech enhancement. In 2018 IEEE 20th International workshop on multimedia signal processing (MMSP), 1–5. IEEE, 2018. URL: https://doi.org/10.1109/MMSP.2018.8547084." which is also referenced on the page. You can see the details of the training there. This model is a simplified version of that paper, not tuned well, has suboptimal performance, and is thus useful mainly for pedagogical purposes.
