### ISSUE TITLE
Small Typo in Chapter 6.4

### ISSUE THREAD

**Issue by zhouzhao01** [Speech-Interaction-Technology-Aalto-U/itsp#15]
6.4.1.2.3. Box plots

“The red line in the midle represent the median of all scores, the blue box contains 50% of all measurements and the black horizontal lines indicate the largest and lowest scores.”

midel -> middle

6.4.1.2.1. Histograms
The Histograms' mean, std and colors don not match with the descriptions.

Thanks for generously making this great book open-source!

**Comment by tombackstrom** [comment]
Thank you! I ran an automated grammar check on the whole section and found loads of similar minor issues that I could fix. Your help is appreciated!
